-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS teenpay.schools
(
    id bigserial NOT NULL,
    code text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    city text COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    account_number text COLLATE pg_catalog."default",
    payment_code text COLLATE pg_catalog."default" NOT NULL,
    pos_user_id integer,
    CONSTRAINT schools_pkey PRIMARY KEY (id),
    CONSTRAINT schools_code_key UNIQUE (code),
    CONSTRAINT schools_payment_code_uk UNIQUE (payment_code)
);

CREATE TABLE IF NOT EXISTS teenpay.users
(
    id bigserial NOT NULL,
    email text COLLATE pg_catalog."default",
    phone text COLLATE pg_catalog."default",
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    locale text COLLATE pg_catalog."default" DEFAULT 'en'::text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    username text COLLATE pg_catalog."default" NOT NULL,
    first_name text COLLATE pg_catalog."default",
    last_name text COLLATE pg_catalog."default",
    role text COLLATE pg_catalog."default",
    balance numeric(12, 2) NOT NULL DEFAULT 0,
    personal_code text COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_phone_key UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS classifiers.roles
(
    id bigserial NOT NULL,
    code text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS teenpay.authorities
(
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    granted_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT authorities_pkey PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS teenpay.refresh_tokens
(
    id serial NOT NULL,
    token text COLLATE pg_catalog."default" NOT NULL,
    expires_at_utc timestamp with time zone NOT NULL,
    created_at_utc timestamp with time zone NOT NULL DEFAULT now(),
    device_id text COLLATE pg_catalog."default",
    revoked boolean NOT NULL DEFAULT false,
    user_id integer NOT NULL,
    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS teenpay.transactions
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    amount numeric(12, 2) NOT NULL,
    kind text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    school_id bigint,
    child_id bigint,
    CONSTRAINT transactions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS teenpay.student_schools
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    school_id integer NOT NULL,
    CONSTRAINT student_schools_pkey PRIMARY KEY (id),
    CONSTRAINT student_schools_user_id_school_id_key UNIQUE (user_id, school_id)
);

CREATE TABLE IF NOT EXISTS teenpay.parent_children
(
    id bigserial NOT NULL,
    parent_user_id integer NOT NULL,
    child_user_id integer NOT NULL,
    CONSTRAINT parent_children_pkey PRIMARY KEY (id),
    CONSTRAINT parent_children_parent_user_id_child_user_id_key UNIQUE (parent_user_id, child_user_id)
);

CREATE TABLE IF NOT EXISTS teenpay.topup_requests
(
    id bigserial NOT NULL,
    child_id bigint NOT NULL,
    parent_id bigint NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::text,
    requested_at timestamp with time zone NOT NULL DEFAULT now(),
    approved_at timestamp with time zone,
    note text COLLATE pg_catalog."default",
    CONSTRAINT topup_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS teenpay.receipts
(
    id bigserial NOT NULL,
    receipt_no character varying(8) COLLATE pg_catalog."default" NOT NULL,
    amount numeric(12, 2) NOT NULL,
    kind text COLLATE pg_catalog."default" NOT NULL,
    payer_user_id integer NOT NULL,
    payee_user_id integer NOT NULL,
    school_id bigint,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT receipts_pkey PRIMARY KEY (id),
    CONSTRAINT receipts_receipt_no_key UNIQUE (receipt_no)
);

ALTER TABLE IF EXISTS teenpay.schools
    ADD CONSTRAINT fk_schools_pos_user FOREIGN KEY (pos_user_id)
    REFERENCES teenpay.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS ix_schools_pos_user_id
    ON teenpay.schools(pos_user_id);


ALTER TABLE IF EXISTS teenpay.users
    ADD CONSTRAINT users_role_fk FOREIGN KEY (role)
    REFERENCES classifiers.roles (code) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS teenpay.authorities
    ADD CONSTRAINT authorities_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES classifiers.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS teenpay.authorities
    ADD CONSTRAINT authorities_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES teenpay.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS teenpay.refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES teenpay.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS teenpay.transactions
    ADD CONSTRAINT transactions_child_fk FOREIGN KEY (child_id)
    REFERENCES teenpay.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS teenpay.transactions
    ADD CONSTRAINT transactions_school_fk FOREIGN KEY (school_id)
    REFERENCES teenpay.schools (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS teenpay.transactions
    ADD CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES teenpay.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS teenpay.student_schools
    ADD CONSTRAINT student_schools_school_id_fkey FOREIGN KEY (school_id)
    REFERENCES teenpay.schools (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS teenpay.student_schools
    ADD CONSTRAINT student_schools_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES teenpay.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS teenpay.parent_children
    ADD CONSTRAINT parent_children_child_user_id_fkey FOREIGN KEY (child_user_id)
    REFERENCES teenpay.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS teenpay.parent_children
    ADD CONSTRAINT parent_children_parent_user_id_fkey FOREIGN KEY (parent_user_id)
    REFERENCES teenpay.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS teenpay.topup_requests
    ADD CONSTRAINT topup_requests_child_id_fkey FOREIGN KEY (child_id)
    REFERENCES teenpay.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS teenpay.topup_requests
    ADD CONSTRAINT topup_requests_parent_id_fkey FOREIGN KEY (parent_id)
    REFERENCES teenpay.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS teenpay.receipts
    ADD CONSTRAINT receipts_payee_user_id_fkey FOREIGN KEY (payee_user_id)
    REFERENCES teenpay.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_receipts_payee
    ON teenpay.receipts(payee_user_id);


ALTER TABLE IF EXISTS teenpay.receipts
    ADD CONSTRAINT receipts_payer_user_id_fkey FOREIGN KEY (payer_user_id)
    REFERENCES teenpay.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_receipts_payer
    ON teenpay.receipts(payer_user_id);


ALTER TABLE IF EXISTS teenpay.receipts
    ADD CONSTRAINT receipts_school_id_fkey FOREIGN KEY (school_id)
    REFERENCES teenpay.schools (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;